config/routes.rb
Rails.application.routes.draw do
    root 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params[:home]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_contact.html.erb
<div class= 'container appt'>
<h3>Contact Us to Book an Appointment</h3>

                        <div class="clearfix"></div>
                    <div class="space"></div>
                        <div class="col-sm-6">
                            <div class="contact-content">

                        <div class="col-sm-6">
                            <div class="footer-content">
                                <form role="form" id="footer-form">
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="name2">Name</label>
                                        <input type="text" class="form-control" id="name2" placeholder="Name" name="name2" required>
                                        <i class="fa fa-user form-control-feedback"></i>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="email2">Email address</label>
                                        <input type="email" class="form-control" id="email2" placeholder="Enter email" name="email2" required>
                                        <i class="fa fa-envelope form-control-feedback"></i>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="message2">Message</label>
                                        <textarea class="form-control" rows="8" id="message2" placeholder="Message" name="message2" required></textarea>
                                        <i class="fa fa-pencil form-control-feedback"></i>
                                    </div>
                                    <input type="submit" value="Send" class="btn btn-default">
                                </form>
                                                                <ul class="list-icons">
                                    <li><i class="fa fa-map-marker pr-10"></i> 2435 N. Central Expressway, Suite 1200 Richardson, TX 75080</li>
                                    <li><i class="fa fa-phone pr-10"></i> (469) 999-6611 1234567890</li>
                                    <li><i class="fa fa-envelope-o pr-10"></i> Express Roofing Contractors USA</li>
        </ul>
                            </div>
                        </div>
                        </div>
                        </div>
                        </div>

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/_rightcontact.html.erb
<div class= 'container'>
                        <div class="col-sm-6">
                            <div class="footer-content">
                                <form role="form" id="footer-form">
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="name2">Name</label>
                                        <input type="text" class="form-control" id="name2" placeholder="Name" name="name2" required>
                                        <i class="fa fa-user form-control-feedback"></i>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="email2">Email address</label>
                                        <input type="email" class="form-control" id="email2" placeholder="Enter email" name="email2" required>
                                        <i class="fa fa-envelope form-control-feedback"></i>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="message2">Message</label>
                                        <textarea class="form-control" rows="8" id="message2" placeholder="Message" name="message2" required></textarea>
                                        <i class="fa fa-pencil form-control-feedback"></i>
                                    </div>
                                    <input type="submit" value="Send" class="btn btn-default">
                                </form>
                                                                <ul class="list-icons">
                                    <li><i class="fa fa-map-marker pr-10"></i> 2435 N. Central Expressway, Suite 1200 Richardson, TX 75080</li>
                                    <li><i class="fa fa-phone pr-10"></i> (469) 999-6611 1234567890</li>
                                    <li><i class="fa fa-envelope-o pr-10"></i> Express Roofing Contractors USA</li>
        </ul>
                            </div>
                        </div>
                        </div>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/jsindex.html.erb
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag 'texas_flag.jpg'%>
       <div class="carousel-caption">
        <h3>We're Proud of our Texas Roots</h3>
        <p>Express Roofing USA is a Texas company, so naturally we build roofs the Texas way. Strong. Tough. Durable. Long-Lasting. We believe in the quality of our work, that's why we provide a guarantee from start to finish.</p>
      </div>
        </div>

      <div class="item">
          <%= image_tag 'Logo-1.png'%>
      </div>




    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
            <ul class="nav pull-right scroll-down">
  <li title="Scroll down"><i class="glyphicon glyphicon-chevron-down"></i></li>
</ul>


<br>
<br>
<br>
<h1 class='do'>What We Do</h1>
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="box">
                            <div class="box-gray aligncenter">
                                <h3>Free Inspections</h3><br>
                                <div class="icon">
                                    <%= image_tag 'free_inspections.jpg', width: '100%' %>
                                </div><br>
                                <h4>
                                  Woried about the hail storm? We provide free inspections to provide you peace of mind.
                                </h4>

                            </div>
                            <div class="box-bottom">
                                <a href="#"><h3>Learn more</h3></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="box">
                            <div class="box-gray aligncenter">
                                <h3>Free Estimates</h3><br>
                                <div class="icon">
                                    <%= image_tag 'estimates.jpg', width: '100%' %>
                                </div><br>
                                <h4>
                                Give us a call or send us an e-mail for your free, no obligation estimate.
                                </h4>

                            </div>
                            <div class="box-bottom">
                                <a href="#"><h3>Learn more</h3></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="box">
                            <div class="box-gray aligncenter">
                                    <h3>Services</h3><br>
                                <div class="icon">
                                    <%= image_tag 'services.jpg', width: '100%' %>
                                </div><br>
                                <h4>
                                 We install roofs for every type of property and use only the best material.
                                </h4>
                            </div>
                            <div class="box-bottom">
                                <a href="#"><h3>Learn more</h3></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="box">
                            <div class="box-gray aligncenter">
                                    <h3>Our Work</h3><br>
                                <div class="icon">
                                    <%= image_tag 'work1.jpg', width: '100%' %>
                                </div><br>
                                <h4>
                                 A good roof is the foundation of a good home. That's why we only use the best materials.
                                </h4>

                            </div>
                            <div class="box-bottom">
                                <a href="#"><h3>Learn more</h3></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        <!-- divider -->
        <div class="row">
            <div class="col-lg-12">
                <div class="solidline">
                </div>
            </div>
        </div>
<br><br>
      <div id="map-canvas"></div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/_footer.html.erb
<!-- footer start -->
        <!-- ================ -->
        <footer id="express-footer">

            <!-- .footer start -->
            <!-- ================ -->
            <div class="footer section">
                <div class="container">
                    <h1 class="footer-title text-center" id="contact">Contact Us</h1>
                    <div class="line">
                            <hr class="footer-line">
                        </div>
                        <div class="clearfix"></div>
                    <div class="space"></div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="footer-content">
                               <p class="large">Please feel free to drop us a line with the form on the right or via email. If you have any pressing questions don't hesitate to call at the number below. If you would rather meet in person, feel free to stop by our office.</p>
                                <ul class="list-icons">
                                    <li><i class="fa fa-map-marker pr-10"></i> 2435 N. Central Expressway, Suite 1200 Richardson, TX 75080</li>
                                    <li><i class="fa fa-phone pr-10"></i> (469) 999-6611 1234567890</li>
                                    <li><i class="fa fa-envelope-o pr-10"></i> Express Roofing Contractors USA</li>
                                </ul>
                                <ul class="social-links">
                                    <li class="facebook"><a target="_blank" href="https://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
                                    <li class="twitter"><a target="_blank" href="https://twitter.com"><i class="fa fa-twitter"></i></a></li>
                                    <li class="googleplus"><a target="_blank" href="http://plus.google.com"><i class="fa fa-google-plus"></i></a></li>
                                    <li class="skype"><a target="_blank" href="http://www.skype.com"><i class="fa fa-skype"></i></a></li>
                                    <li class="linkedin"><a target="_blank" href="http://www.linkedin.com"><i class="fa fa-linkedin"></i></a></li>
                                    <li class="youtube"><a target="_blank" href="http://www.youtube.com"><i class="fa fa-youtube"></i></a></li>
                                    <li class="flickr"><a target="_blank" href="http://www.flickr.com"><i class="fa fa-flickr"></i></a></li>
                                    <li class="pinterest"><a target="_blank" href="http://www.pinterest.com"><i class="fa fa-pinterest"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="footer-content">
                                <form role="form" id="footer-form">
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="name2">Name</label>
                                        <input type="text" class="form-control" id="name2" placeholder="Name" name="name2" required>
                                        <i class="fa fa-user form-control-feedback"></i>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="email2">Email address</label>
                                        <input type="email" class="form-control" id="email2" placeholder="Enter email" name="email2" required>
                                        <i class="fa fa-envelope form-control-feedback"></i>
                                    </div>
                                    <div class="form-group has-feedback">
                                        <label class="sr-only" for="message2">Message</label>
                                        <textarea class="form-control" rows="8" id="message2" placeholder="Message" name="message2" required></textarea>
                                        <i class="fa fa-pencil form-control-feedback"></i>
                                    </div>
                                    <input type="submit" value="Send" class="btn btn-default">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- .footer end -->

            <!-- .subfooter start -->
            <!-- ================ -->
            <div class="subfooter">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">

                            <p class="text-center"><span>&copy; Express Roofing Contractors USA 2015 All right reserved.</p></span>
                            <p class="text-center squad"><a href="http://squadcreative.com" target="_blank">Delivered by Squ@d Creative</a></p>

                        </div>
                    </div>
                </div>
            </div>
            <!-- .subfooter end -->

        </footer>
        <!-- footer end -->

app/views/layouts/_navbar.html.erb
<nav id="express-menu" class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#express-home">Express Roofing Contractors</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#express-home" class="page-scroll">Home</a></li>
            <li><a href="#express-about" class="page-scroll">About</a></li>
            <li><a href="#express-services" class="page-scroll">Services</a></li>
            <li><a href="#express-portfolio" class="page-scroll">Portfolio</a></li>
            <li><a href="#express-footer" class="page-scroll">Contact</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpressRoofing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<meta name="viewport" content="width=device-width, initial-scale=1"/>

<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->


<!-- Google Fonts
    ================================================== -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,700,400' rel='stylesheet' type='text/css'>
<!-- End
    ================================================== -->
    <%= csrf_meta_tags %>
</head>
<body data-spy="scroll">
    <%= render 'layouts/navbar'%>
<div class='stuff'>
<%= yield %>
    </div>
    <%= render 'layouts/footer'%>


</body>
</html>